server:
  port: 8883
  servlet:
    context-path: /students-app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students
    username: root
    password: 123
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update